// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trading.proto

package org.anhonesteffort.trading.proto;

public final class TradingProto {
  private TradingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .BaseMessage.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .BaseMessage.Type type = 1;</code>
     */
    org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type getType();

    /**
     * <code>optional .Error error = 2;</code>
     */
    boolean hasError();
    /**
     * <code>optional .Error error = 2;</code>
     */
    org.anhonesteffort.trading.proto.TradingProto.Error getError();
    /**
     * <code>optional .Error error = 2;</code>
     */
    org.anhonesteffort.trading.proto.TradingProto.ErrorOrBuilder getErrorOrBuilder();

    /**
     * <code>optional .OrderEvent orderEvent = 3;</code>
     */
    boolean hasOrderEvent();
    /**
     * <code>optional .OrderEvent orderEvent = 3;</code>
     */
    org.anhonesteffort.trading.proto.TradingProto.OrderEvent getOrderEvent();
    /**
     * <code>optional .OrderEvent orderEvent = 3;</code>
     */
    org.anhonesteffort.trading.proto.TradingProto.OrderEventOrBuilder getOrderEventOrBuilder();
  }
  /**
   * Protobuf type {@code BaseMessage}
   */
  public  static final class BaseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseMessage)
      BaseMessageOrBuilder {
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMessage() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              org.anhonesteffort.trading.proto.TradingProto.Error.Builder subBuilder = null;
              if (error_ != null) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(org.anhonesteffort.trading.proto.TradingProto.Error.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Builder subBuilder = null;
              if (orderEvent_ != null) {
                subBuilder = orderEvent_.toBuilder();
              }
              orderEvent_ = input.readMessage(org.anhonesteffort.trading.proto.TradingProto.OrderEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(orderEvent_);
                orderEvent_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.anhonesteffort.trading.proto.TradingProto.internal_static_BaseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.anhonesteffort.trading.proto.TradingProto.internal_static_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.anhonesteffort.trading.proto.TradingProto.BaseMessage.class, org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code BaseMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ERROR = 0;</code>
       */
      ERROR(0),
      /**
       * <code>ORDER_EVENT = 1;</code>
       */
      ORDER_EVENT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ERROR = 0;</code>
       */
      public static final int ERROR_VALUE = 0;
      /**
       * <code>ORDER_EVENT = 1;</code>
       */
      public static final int ORDER_EVENT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return ERROR;
          case 1: return ORDER_EVENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.anhonesteffort.trading.proto.TradingProto.BaseMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BaseMessage.Type)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .BaseMessage.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .BaseMessage.Type type = 1;</code>
     */
    public org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type getType() {
      org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type result = org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type.valueOf(type_);
      return result == null ? org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type.UNRECOGNIZED : result;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private org.anhonesteffort.trading.proto.TradingProto.Error error_;
    /**
     * <code>optional .Error error = 2;</code>
     */
    public boolean hasError() {
      return error_ != null;
    }
    /**
     * <code>optional .Error error = 2;</code>
     */
    public org.anhonesteffort.trading.proto.TradingProto.Error getError() {
      return error_ == null ? org.anhonesteffort.trading.proto.TradingProto.Error.getDefaultInstance() : error_;
    }
    /**
     * <code>optional .Error error = 2;</code>
     */
    public org.anhonesteffort.trading.proto.TradingProto.ErrorOrBuilder getErrorOrBuilder() {
      return getError();
    }

    public static final int ORDEREVENT_FIELD_NUMBER = 3;
    private org.anhonesteffort.trading.proto.TradingProto.OrderEvent orderEvent_;
    /**
     * <code>optional .OrderEvent orderEvent = 3;</code>
     */
    public boolean hasOrderEvent() {
      return orderEvent_ != null;
    }
    /**
     * <code>optional .OrderEvent orderEvent = 3;</code>
     */
    public org.anhonesteffort.trading.proto.TradingProto.OrderEvent getOrderEvent() {
      return orderEvent_ == null ? org.anhonesteffort.trading.proto.TradingProto.OrderEvent.getDefaultInstance() : orderEvent_;
    }
    /**
     * <code>optional .OrderEvent orderEvent = 3;</code>
     */
    public org.anhonesteffort.trading.proto.TradingProto.OrderEventOrBuilder getOrderEventOrBuilder() {
      return getOrderEvent();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type.ERROR.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (error_ != null) {
        output.writeMessage(2, getError());
      }
      if (orderEvent_ != null) {
        output.writeMessage(3, getOrderEvent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type.ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (error_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getError());
      }
      if (orderEvent_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getOrderEvent());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.anhonesteffort.trading.proto.TradingProto.BaseMessage)) {
        return super.equals(obj);
      }
      org.anhonesteffort.trading.proto.TradingProto.BaseMessage other = (org.anhonesteffort.trading.proto.TradingProto.BaseMessage) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (hasError() == other.hasError());
      if (hasError()) {
        result = result && getError()
            .equals(other.getError());
      }
      result = result && (hasOrderEvent() == other.hasOrderEvent());
      if (hasOrderEvent()) {
        result = result && getOrderEvent()
            .equals(other.getOrderEvent());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      if (hasOrderEvent()) {
        hash = (37 * hash) + ORDEREVENT_FIELD_NUMBER;
        hash = (53 * hash) + getOrderEvent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.anhonesteffort.trading.proto.TradingProto.BaseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseMessage)
        org.anhonesteffort.trading.proto.TradingProto.BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.anhonesteffort.trading.proto.TradingProto.internal_static_BaseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.anhonesteffort.trading.proto.TradingProto.internal_static_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.anhonesteffort.trading.proto.TradingProto.BaseMessage.class, org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Builder.class);
      }

      // Construct using org.anhonesteffort.trading.proto.TradingProto.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (errorBuilder_ == null) {
          error_ = null;
        } else {
          error_ = null;
          errorBuilder_ = null;
        }
        if (orderEventBuilder_ == null) {
          orderEvent_ = null;
        } else {
          orderEvent_ = null;
          orderEventBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.anhonesteffort.trading.proto.TradingProto.internal_static_BaseMessage_descriptor;
      }

      public org.anhonesteffort.trading.proto.TradingProto.BaseMessage getDefaultInstanceForType() {
        return org.anhonesteffort.trading.proto.TradingProto.BaseMessage.getDefaultInstance();
      }

      public org.anhonesteffort.trading.proto.TradingProto.BaseMessage build() {
        org.anhonesteffort.trading.proto.TradingProto.BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.anhonesteffort.trading.proto.TradingProto.BaseMessage buildPartial() {
        org.anhonesteffort.trading.proto.TradingProto.BaseMessage result = new org.anhonesteffort.trading.proto.TradingProto.BaseMessage(this);
        result.type_ = type_;
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        if (orderEventBuilder_ == null) {
          result.orderEvent_ = orderEvent_;
        } else {
          result.orderEvent_ = orderEventBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.anhonesteffort.trading.proto.TradingProto.BaseMessage) {
          return mergeFrom((org.anhonesteffort.trading.proto.TradingProto.BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.anhonesteffort.trading.proto.TradingProto.BaseMessage other) {
        if (other == org.anhonesteffort.trading.proto.TradingProto.BaseMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        if (other.hasOrderEvent()) {
          mergeOrderEvent(other.getOrderEvent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.anhonesteffort.trading.proto.TradingProto.BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.anhonesteffort.trading.proto.TradingProto.BaseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .BaseMessage.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .BaseMessage.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .BaseMessage.Type type = 1;</code>
       */
      public org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type getType() {
        org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type result = org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type.valueOf(type_);
        return result == null ? org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .BaseMessage.Type type = 1;</code>
       */
      public Builder setType(org.anhonesteffort.trading.proto.TradingProto.BaseMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .BaseMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private org.anhonesteffort.trading.proto.TradingProto.Error error_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.anhonesteffort.trading.proto.TradingProto.Error, org.anhonesteffort.trading.proto.TradingProto.Error.Builder, org.anhonesteffort.trading.proto.TradingProto.ErrorOrBuilder> errorBuilder_;
      /**
       * <code>optional .Error error = 2;</code>
       */
      public boolean hasError() {
        return errorBuilder_ != null || error_ != null;
      }
      /**
       * <code>optional .Error error = 2;</code>
       */
      public org.anhonesteffort.trading.proto.TradingProto.Error getError() {
        if (errorBuilder_ == null) {
          return error_ == null ? org.anhonesteffort.trading.proto.TradingProto.Error.getDefaultInstance() : error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Error error = 2;</code>
       */
      public Builder setError(org.anhonesteffort.trading.proto.TradingProto.Error value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Error error = 2;</code>
       */
      public Builder setError(
          org.anhonesteffort.trading.proto.TradingProto.Error.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Error error = 2;</code>
       */
      public Builder mergeError(org.anhonesteffort.trading.proto.TradingProto.Error value) {
        if (errorBuilder_ == null) {
          if (error_ != null) {
            error_ =
              org.anhonesteffort.trading.proto.TradingProto.Error.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Error error = 2;</code>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = null;
          onChanged();
        } else {
          error_ = null;
          errorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Error error = 2;</code>
       */
      public org.anhonesteffort.trading.proto.TradingProto.Error.Builder getErrorBuilder() {
        
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Error error = 2;</code>
       */
      public org.anhonesteffort.trading.proto.TradingProto.ErrorOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_ == null ?
              org.anhonesteffort.trading.proto.TradingProto.Error.getDefaultInstance() : error_;
        }
      }
      /**
       * <code>optional .Error error = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.anhonesteffort.trading.proto.TradingProto.Error, org.anhonesteffort.trading.proto.TradingProto.Error.Builder, org.anhonesteffort.trading.proto.TradingProto.ErrorOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.anhonesteffort.trading.proto.TradingProto.Error, org.anhonesteffort.trading.proto.TradingProto.Error.Builder, org.anhonesteffort.trading.proto.TradingProto.ErrorOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      private org.anhonesteffort.trading.proto.TradingProto.OrderEvent orderEvent_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.anhonesteffort.trading.proto.TradingProto.OrderEvent, org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Builder, org.anhonesteffort.trading.proto.TradingProto.OrderEventOrBuilder> orderEventBuilder_;
      /**
       * <code>optional .OrderEvent orderEvent = 3;</code>
       */
      public boolean hasOrderEvent() {
        return orderEventBuilder_ != null || orderEvent_ != null;
      }
      /**
       * <code>optional .OrderEvent orderEvent = 3;</code>
       */
      public org.anhonesteffort.trading.proto.TradingProto.OrderEvent getOrderEvent() {
        if (orderEventBuilder_ == null) {
          return orderEvent_ == null ? org.anhonesteffort.trading.proto.TradingProto.OrderEvent.getDefaultInstance() : orderEvent_;
        } else {
          return orderEventBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .OrderEvent orderEvent = 3;</code>
       */
      public Builder setOrderEvent(org.anhonesteffort.trading.proto.TradingProto.OrderEvent value) {
        if (orderEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orderEvent_ = value;
          onChanged();
        } else {
          orderEventBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .OrderEvent orderEvent = 3;</code>
       */
      public Builder setOrderEvent(
          org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Builder builderForValue) {
        if (orderEventBuilder_ == null) {
          orderEvent_ = builderForValue.build();
          onChanged();
        } else {
          orderEventBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .OrderEvent orderEvent = 3;</code>
       */
      public Builder mergeOrderEvent(org.anhonesteffort.trading.proto.TradingProto.OrderEvent value) {
        if (orderEventBuilder_ == null) {
          if (orderEvent_ != null) {
            orderEvent_ =
              org.anhonesteffort.trading.proto.TradingProto.OrderEvent.newBuilder(orderEvent_).mergeFrom(value).buildPartial();
          } else {
            orderEvent_ = value;
          }
          onChanged();
        } else {
          orderEventBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .OrderEvent orderEvent = 3;</code>
       */
      public Builder clearOrderEvent() {
        if (orderEventBuilder_ == null) {
          orderEvent_ = null;
          onChanged();
        } else {
          orderEvent_ = null;
          orderEventBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .OrderEvent orderEvent = 3;</code>
       */
      public org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Builder getOrderEventBuilder() {
        
        onChanged();
        return getOrderEventFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .OrderEvent orderEvent = 3;</code>
       */
      public org.anhonesteffort.trading.proto.TradingProto.OrderEventOrBuilder getOrderEventOrBuilder() {
        if (orderEventBuilder_ != null) {
          return orderEventBuilder_.getMessageOrBuilder();
        } else {
          return orderEvent_ == null ?
              org.anhonesteffort.trading.proto.TradingProto.OrderEvent.getDefaultInstance() : orderEvent_;
        }
      }
      /**
       * <code>optional .OrderEvent orderEvent = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.anhonesteffort.trading.proto.TradingProto.OrderEvent, org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Builder, org.anhonesteffort.trading.proto.TradingProto.OrderEventOrBuilder> 
          getOrderEventFieldBuilder() {
        if (orderEventBuilder_ == null) {
          orderEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.anhonesteffort.trading.proto.TradingProto.OrderEvent, org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Builder, org.anhonesteffort.trading.proto.TradingProto.OrderEventOrBuilder>(
                  getOrderEvent(),
                  getParentForChildren(),
                  isClean());
          orderEvent_ = null;
        }
        return orderEventBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BaseMessage)
    }

    // @@protoc_insertion_point(class_scope:BaseMessage)
    private static final org.anhonesteffort.trading.proto.TradingProto.BaseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.anhonesteffort.trading.proto.TradingProto.BaseMessage();
    }

    public static org.anhonesteffort.trading.proto.TradingProto.BaseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMessage>
        PARSER = new com.google.protobuf.AbstractParser<BaseMessage>() {
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BaseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    public org.anhonesteffort.trading.proto.TradingProto.BaseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Error)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code Error}
   */
  public  static final class Error extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Error)
      ErrorOrBuilder {
    // Use Error.newBuilder() to construct.
    private Error(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Error() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Error(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.anhonesteffort.trading.proto.TradingProto.internal_static_Error_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.anhonesteffort.trading.proto.TradingProto.internal_static_Error_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.anhonesteffort.trading.proto.TradingProto.Error.class, org.anhonesteffort.trading.proto.TradingProto.Error.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>optional string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>optional string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.anhonesteffort.trading.proto.TradingProto.Error)) {
        return super.equals(obj);
      }
      org.anhonesteffort.trading.proto.TradingProto.Error other = (org.anhonesteffort.trading.proto.TradingProto.Error) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.anhonesteffort.trading.proto.TradingProto.Error parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.Error parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.Error parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.Error parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.Error parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.Error parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.Error parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.Error parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.Error parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.Error parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.anhonesteffort.trading.proto.TradingProto.Error prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Error}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Error)
        org.anhonesteffort.trading.proto.TradingProto.ErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.anhonesteffort.trading.proto.TradingProto.internal_static_Error_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.anhonesteffort.trading.proto.TradingProto.internal_static_Error_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.anhonesteffort.trading.proto.TradingProto.Error.class, org.anhonesteffort.trading.proto.TradingProto.Error.Builder.class);
      }

      // Construct using org.anhonesteffort.trading.proto.TradingProto.Error.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.anhonesteffort.trading.proto.TradingProto.internal_static_Error_descriptor;
      }

      public org.anhonesteffort.trading.proto.TradingProto.Error getDefaultInstanceForType() {
        return org.anhonesteffort.trading.proto.TradingProto.Error.getDefaultInstance();
      }

      public org.anhonesteffort.trading.proto.TradingProto.Error build() {
        org.anhonesteffort.trading.proto.TradingProto.Error result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.anhonesteffort.trading.proto.TradingProto.Error buildPartial() {
        org.anhonesteffort.trading.proto.TradingProto.Error result = new org.anhonesteffort.trading.proto.TradingProto.Error(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.anhonesteffort.trading.proto.TradingProto.Error) {
          return mergeFrom((org.anhonesteffort.trading.proto.TradingProto.Error)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.anhonesteffort.trading.proto.TradingProto.Error other) {
        if (other == org.anhonesteffort.trading.proto.TradingProto.Error.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.anhonesteffort.trading.proto.TradingProto.Error parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.anhonesteffort.trading.proto.TradingProto.Error) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Error)
    }

    // @@protoc_insertion_point(class_scope:Error)
    private static final org.anhonesteffort.trading.proto.TradingProto.Error DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.anhonesteffort.trading.proto.TradingProto.Error();
    }

    public static org.anhonesteffort.trading.proto.TradingProto.Error getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Error>
        PARSER = new com.google.protobuf.AbstractParser<Error>() {
      public Error parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Error(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Error> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Error> getParserForType() {
      return PARSER;
    }

    public org.anhonesteffort.trading.proto.TradingProto.Error getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .OrderEvent.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .OrderEvent.Type type = 1;</code>
     */
    org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type getType();

    /**
     * <code>optional int64 timeMs = 2;</code>
     */
    long getTimeMs();

    /**
     * <code>optional int64 timeNs = 3;</code>
     */
    long getTimeNs();

    /**
     * <code>optional string orderId = 4;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>optional string orderId = 4;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>optional .OrderEvent.Side side = 5;</code>
     */
    int getSideValue();
    /**
     * <code>optional .OrderEvent.Side side = 5;</code>
     */
    org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side getSide();

    /**
     * <code>optional double price = 6;</code>
     */
    double getPrice();

    /**
     * <code>optional double size = 7;</code>
     */
    double getSize();
  }
  /**
   * Protobuf type {@code OrderEvent}
   */
  public  static final class OrderEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OrderEvent)
      OrderEventOrBuilder {
    // Use OrderEvent.newBuilder() to construct.
    private OrderEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderEvent() {
      type_ = 0;
      timeMs_ = 0L;
      timeNs_ = 0L;
      orderId_ = "";
      side_ = 0;
      price_ = 0D;
      size_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OrderEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              timeMs_ = input.readInt64();
              break;
            }
            case 24: {

              timeNs_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              orderId_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              side_ = rawValue;
              break;
            }
            case 49: {

              price_ = input.readDouble();
              break;
            }
            case 57: {

              size_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.anhonesteffort.trading.proto.TradingProto.internal_static_OrderEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.anhonesteffort.trading.proto.TradingProto.internal_static_OrderEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.anhonesteffort.trading.proto.TradingProto.OrderEvent.class, org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Builder.class);
    }

    /**
     * Protobuf enum {@code OrderEvent.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OPEN = 0;</code>
       */
      OPEN(0),
      /**
       * <code>TAKE = 1;</code>
       */
      TAKE(1),
      /**
       * <code>REDUCE = 2;</code>
       */
      REDUCE(2),
      /**
       * <code>SYNC_START = 3;</code>
       */
      SYNC_START(3),
      /**
       * <code>SYNC_END = 4;</code>
       */
      SYNC_END(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>OPEN = 0;</code>
       */
      public static final int OPEN_VALUE = 0;
      /**
       * <code>TAKE = 1;</code>
       */
      public static final int TAKE_VALUE = 1;
      /**
       * <code>REDUCE = 2;</code>
       */
      public static final int REDUCE_VALUE = 2;
      /**
       * <code>SYNC_START = 3;</code>
       */
      public static final int SYNC_START_VALUE = 3;
      /**
       * <code>SYNC_END = 4;</code>
       */
      public static final int SYNC_END_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return OPEN;
          case 1: return TAKE;
          case 2: return REDUCE;
          case 3: return SYNC_START;
          case 4: return SYNC_END;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.anhonesteffort.trading.proto.TradingProto.OrderEvent.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:OrderEvent.Type)
    }

    /**
     * Protobuf enum {@code OrderEvent.Side}
     */
    public enum Side
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ASK = 0;</code>
       */
      ASK(0),
      /**
       * <code>BID = 1;</code>
       */
      BID(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ASK = 0;</code>
       */
      public static final int ASK_VALUE = 0;
      /**
       * <code>BID = 1;</code>
       */
      public static final int BID_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Side valueOf(int value) {
        return forNumber(value);
      }

      public static Side forNumber(int value) {
        switch (value) {
          case 0: return ASK;
          case 1: return BID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Side>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Side> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Side>() {
              public Side findValueByNumber(int number) {
                return Side.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.anhonesteffort.trading.proto.TradingProto.OrderEvent.getDescriptor().getEnumTypes().get(1);
      }

      private static final Side[] VALUES = values();

      public static Side valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Side(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:OrderEvent.Side)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .OrderEvent.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .OrderEvent.Type type = 1;</code>
     */
    public org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type getType() {
      org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type result = org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type.valueOf(type_);
      return result == null ? org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type.UNRECOGNIZED : result;
    }

    public static final int TIMEMS_FIELD_NUMBER = 2;
    private long timeMs_;
    /**
     * <code>optional int64 timeMs = 2;</code>
     */
    public long getTimeMs() {
      return timeMs_;
    }

    public static final int TIMENS_FIELD_NUMBER = 3;
    private long timeNs_;
    /**
     * <code>optional int64 timeNs = 3;</code>
     */
    public long getTimeNs() {
      return timeNs_;
    }

    public static final int ORDERID_FIELD_NUMBER = 4;
    private volatile java.lang.Object orderId_;
    /**
     * <code>optional string orderId = 4;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string orderId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIDE_FIELD_NUMBER = 5;
    private int side_;
    /**
     * <code>optional .OrderEvent.Side side = 5;</code>
     */
    public int getSideValue() {
      return side_;
    }
    /**
     * <code>optional .OrderEvent.Side side = 5;</code>
     */
    public org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side getSide() {
      org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side result = org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side.valueOf(side_);
      return result == null ? org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side.UNRECOGNIZED : result;
    }

    public static final int PRICE_FIELD_NUMBER = 6;
    private double price_;
    /**
     * <code>optional double price = 6;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int SIZE_FIELD_NUMBER = 7;
    private double size_;
    /**
     * <code>optional double size = 7;</code>
     */
    public double getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type.OPEN.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (timeMs_ != 0L) {
        output.writeInt64(2, timeMs_);
      }
      if (timeNs_ != 0L) {
        output.writeInt64(3, timeNs_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, orderId_);
      }
      if (side_ != org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side.ASK.getNumber()) {
        output.writeEnum(5, side_);
      }
      if (price_ != 0D) {
        output.writeDouble(6, price_);
      }
      if (size_ != 0D) {
        output.writeDouble(7, size_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type.OPEN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (timeMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timeMs_);
      }
      if (timeNs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeNs_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, orderId_);
      }
      if (side_ != org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side.ASK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, side_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, price_);
      }
      if (size_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, size_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.anhonesteffort.trading.proto.TradingProto.OrderEvent)) {
        return super.equals(obj);
      }
      org.anhonesteffort.trading.proto.TradingProto.OrderEvent other = (org.anhonesteffort.trading.proto.TradingProto.OrderEvent) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (getTimeMs()
          == other.getTimeMs());
      result = result && (getTimeNs()
          == other.getTimeNs());
      result = result && getOrderId()
          .equals(other.getOrderId());
      result = result && side_ == other.side_;
      result = result && (
          java.lang.Double.doubleToLongBits(getPrice())
          == java.lang.Double.doubleToLongBits(
              other.getPrice()));
      result = result && (
          java.lang.Double.doubleToLongBits(getSize())
          == java.lang.Double.doubleToLongBits(
              other.getSize()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + TIMEMS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeMs());
      hash = (37 * hash) + TIMENS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeNs());
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      hash = (37 * hash) + SIDE_FIELD_NUMBER;
      hash = (53 * hash) + side_;
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSize()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.anhonesteffort.trading.proto.TradingProto.OrderEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderEvent)
        org.anhonesteffort.trading.proto.TradingProto.OrderEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.anhonesteffort.trading.proto.TradingProto.internal_static_OrderEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.anhonesteffort.trading.proto.TradingProto.internal_static_OrderEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.anhonesteffort.trading.proto.TradingProto.OrderEvent.class, org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Builder.class);
      }

      // Construct using org.anhonesteffort.trading.proto.TradingProto.OrderEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        timeMs_ = 0L;

        timeNs_ = 0L;

        orderId_ = "";

        side_ = 0;

        price_ = 0D;

        size_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.anhonesteffort.trading.proto.TradingProto.internal_static_OrderEvent_descriptor;
      }

      public org.anhonesteffort.trading.proto.TradingProto.OrderEvent getDefaultInstanceForType() {
        return org.anhonesteffort.trading.proto.TradingProto.OrderEvent.getDefaultInstance();
      }

      public org.anhonesteffort.trading.proto.TradingProto.OrderEvent build() {
        org.anhonesteffort.trading.proto.TradingProto.OrderEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.anhonesteffort.trading.proto.TradingProto.OrderEvent buildPartial() {
        org.anhonesteffort.trading.proto.TradingProto.OrderEvent result = new org.anhonesteffort.trading.proto.TradingProto.OrderEvent(this);
        result.type_ = type_;
        result.timeMs_ = timeMs_;
        result.timeNs_ = timeNs_;
        result.orderId_ = orderId_;
        result.side_ = side_;
        result.price_ = price_;
        result.size_ = size_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.anhonesteffort.trading.proto.TradingProto.OrderEvent) {
          return mergeFrom((org.anhonesteffort.trading.proto.TradingProto.OrderEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.anhonesteffort.trading.proto.TradingProto.OrderEvent other) {
        if (other == org.anhonesteffort.trading.proto.TradingProto.OrderEvent.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getTimeMs() != 0L) {
          setTimeMs(other.getTimeMs());
        }
        if (other.getTimeNs() != 0L) {
          setTimeNs(other.getTimeNs());
        }
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (other.side_ != 0) {
          setSideValue(other.getSideValue());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getSize() != 0D) {
          setSize(other.getSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.anhonesteffort.trading.proto.TradingProto.OrderEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.anhonesteffort.trading.proto.TradingProto.OrderEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .OrderEvent.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .OrderEvent.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .OrderEvent.Type type = 1;</code>
       */
      public org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type getType() {
        org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type result = org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type.valueOf(type_);
        return result == null ? org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .OrderEvent.Type type = 1;</code>
       */
      public Builder setType(org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .OrderEvent.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long timeMs_ ;
      /**
       * <code>optional int64 timeMs = 2;</code>
       */
      public long getTimeMs() {
        return timeMs_;
      }
      /**
       * <code>optional int64 timeMs = 2;</code>
       */
      public Builder setTimeMs(long value) {
        
        timeMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timeMs = 2;</code>
       */
      public Builder clearTimeMs() {
        
        timeMs_ = 0L;
        onChanged();
        return this;
      }

      private long timeNs_ ;
      /**
       * <code>optional int64 timeNs = 3;</code>
       */
      public long getTimeNs() {
        return timeNs_;
      }
      /**
       * <code>optional int64 timeNs = 3;</code>
       */
      public Builder setTimeNs(long value) {
        
        timeNs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timeNs = 3;</code>
       */
      public Builder clearTimeNs() {
        
        timeNs_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>optional string orderId = 4;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string orderId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string orderId = 4;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderId = 4;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string orderId = 4;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private int side_ = 0;
      /**
       * <code>optional .OrderEvent.Side side = 5;</code>
       */
      public int getSideValue() {
        return side_;
      }
      /**
       * <code>optional .OrderEvent.Side side = 5;</code>
       */
      public Builder setSideValue(int value) {
        side_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .OrderEvent.Side side = 5;</code>
       */
      public org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side getSide() {
        org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side result = org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side.valueOf(side_);
        return result == null ? org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .OrderEvent.Side side = 5;</code>
       */
      public Builder setSide(org.anhonesteffort.trading.proto.TradingProto.OrderEvent.Side value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        side_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .OrderEvent.Side side = 5;</code>
       */
      public Builder clearSide() {
        
        side_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>optional double price = 6;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>optional double price = 6;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double price = 6;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private double size_ ;
      /**
       * <code>optional double size = 7;</code>
       */
      public double getSize() {
        return size_;
      }
      /**
       * <code>optional double size = 7;</code>
       */
      public Builder setSize(double value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double size = 7;</code>
       */
      public Builder clearSize() {
        
        size_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:OrderEvent)
    }

    // @@protoc_insertion_point(class_scope:OrderEvent)
    private static final org.anhonesteffort.trading.proto.TradingProto.OrderEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.anhonesteffort.trading.proto.TradingProto.OrderEvent();
    }

    public static org.anhonesteffort.trading.proto.TradingProto.OrderEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderEvent>
        PARSER = new com.google.protobuf.AbstractParser<OrderEvent>() {
      public OrderEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OrderEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderEvent> getParserForType() {
      return PARSER;
    }

    public org.anhonesteffort.trading.proto.TradingProto.OrderEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Error_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Error_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rtrading.proto\"\212\001\n\013BaseMessage\022\037\n\004type\030" +
      "\001 \001(\0162\021.BaseMessage.Type\022\025\n\005error\030\002 \001(\0132" +
      "\006.Error\022\037\n\norderEvent\030\003 \001(\0132\013.OrderEvent" +
      "\"\"\n\004Type\022\t\n\005ERROR\020\000\022\017\n\013ORDER_EVENT\020\001\"\030\n\005" +
      "Error\022\017\n\007message\030\001 \001(\t\"\372\001\n\nOrderEvent\022\036\n" +
      "\004type\030\001 \001(\0162\020.OrderEvent.Type\022\016\n\006timeMs\030" +
      "\002 \001(\003\022\016\n\006timeNs\030\003 \001(\003\022\017\n\007orderId\030\004 \001(\t\022\036" +
      "\n\004side\030\005 \001(\0162\020.OrderEvent.Side\022\r\n\005price\030" +
      "\006 \001(\001\022\014\n\004size\030\007 \001(\001\"D\n\004Type\022\010\n\004OPEN\020\000\022\010\n" +
      "\004TAKE\020\001\022\n\n\006REDUCE\020\002\022\016\n\nSYNC_START\020\003\022\014\n\010S",
      "YNC_END\020\004\"\030\n\004Side\022\007\n\003ASK\020\000\022\007\n\003BID\020\001B0\n o" +
      "rg.anhonesteffort.trading.protoB\014Trading" +
      "Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BaseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseMessage_descriptor,
        new java.lang.String[] { "Type", "Error", "OrderEvent", });
    internal_static_Error_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Error_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_OrderEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OrderEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderEvent_descriptor,
        new java.lang.String[] { "Type", "TimeMs", "TimeNs", "OrderId", "Side", "Price", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
